FROM node:18-alpine

ENV VITE_API_URL=http://localhost:8000

WORKDIR /app

# Copy package files
COPY package*.json ./

# Clean npm cache and remove node_modules if exists
RUN npm cache clean --force && rm -rf node_modules

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]